# Generated by Django 5.2.13 on 2026-06-15 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme_id', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__slug', 'theme_id'],
            },
        ),
        migrations.CreateModel(
            name='ThemeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('version', models.CharField(max_length=80)),
                ('schema_version', models.CharField(default='v1', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('payload', models.JSONField()),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_revisions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='themes.theme')),
            ],
            options={
                'ordering': ['theme_id', 'revision'],
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='themes.themerevision'),
        ),
        migrations.AddConstraint(
            model_name='themerevision',
            constraint=models.UniqueConstraint(fields=('theme', 'revision'), name='unique_theme_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(fields=('tenant', 'theme_id'), name='unique_theme_id_per_tenant'),
        ),
    ]
