# Generated by Django 5.2.13 on 2026-06-21 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_builder', '0002_formsubmission'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.SlugField(max_length=128)),
                ('platform', models.CharField(max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=80)),
                ('runtime_version', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], db_index=True, default='active', max_length=16)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__slug', 'device_id'],
            },
        ),
        migrations.CreateModel(
            name='OutboxBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.SlugField(max_length=128)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('partial', 'Partial'), ('rejected', 'Rejected')], db_index=True, max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_batches', to='sync.syncdevice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SyncRejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('message', models.TextField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__slug', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionSyncResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_submission_id', models.SlugField(max_length=128)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected')], db_index=True, max_length=16)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='sync.outboxbatch')),
                ('form_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_results', to='form_builder.formsubmission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('rejection_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_results', to='sync.syncrejectionreason')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('partial', 'Partial'), ('rejected', 'Rejected')], db_index=True, default='accepted', max_length=16)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='sync.syncdevice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='outboxbatch',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='sync.syncsession'),
        ),
        migrations.AddConstraint(
            model_name='syncdevice',
            constraint=models.UniqueConstraint(fields=('tenant', 'device_id'), name='unique_sync_device_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='syncrejectionreason',
            constraint=models.UniqueConstraint(fields=('tenant', 'code', 'message'), name='unique_sync_rejection_reason'),
        ),
        migrations.AddConstraint(
            model_name='submissionsyncresult',
            constraint=models.UniqueConstraint(fields=('tenant', 'client_submission_id'), name='unique_sync_client_submission_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='outboxbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'device', 'batch_id'), name='unique_outbox_batch_per_device'),
        ),
    ]
