# Generated by Django 5.2.13 on 2026-06-16 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("form_id", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("mode", models.CharField(max_length=16)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
            ],
            options={
                "ordering": ["tenant__slug", "form_id"],
            },
        ),
        migrations.CreateModel(
            name="FormRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField()),
                ("version", models.CharField(max_length=80)),
                ("schema_version", models.CharField(default="v1", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField()),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="form_builder.formdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["form_id", "revision"],
            },
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="form_builder.formrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="formrevision",
            constraint=models.UniqueConstraint(fields=("form", "revision"), name="unique_form_revision_number"),
        ),
        migrations.AddConstraint(
            model_name="formdefinition",
            constraint=models.UniqueConstraint(fields=("tenant", "form_id"), name="unique_form_id_per_tenant"),
        ),
    ]
