from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path
from typing import Any

try:
    from .validate_contracts import DEFAULT_MANIFEST, load_manifest, load_schemas
except ImportError:  # pragma: no cover - used when executed as a direct script.
    from validate_contracts import DEFAULT_MANIFEST, load_manifest, load_schemas


CONTRACTS_ROOT = Path(__file__).resolve().parent
DEFAULT_TYPESCRIPT_OUTPUT = CONTRACTS_ROOT / "generated" / "typescript" / "v1" / "contracts.d.ts"
DEFAULT_PYTHON_OUTPUT = CONTRACTS_ROOT / "generated" / "python" / "v1" / "contracts.py"


class TypeGenerationError(RuntimeError):
    pass


def pascal_case(value: str) -> str:
    words = re.split(r"[^A-Za-z0-9]+", value)
    return "".join(word[:1].upper() + word[1:] for word in words if word)


def type_name_for_schema(schema: dict[str, Any], fallback: str) -> str:
    return pascal_case(schema.get("title") or fallback)


def literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return repr(value).replace('"', '\\"').replace("'", '"')
    return str(value)


def python_literal(value: Any) -> str:
    if value is None:
        return "None"
    return repr(value)


def check_output(output_path: Path, expected: str, label: str) -> None:
    actual = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
    if actual != expected:
        diff = "\n".join(
            difflib.unified_diff(
                actual.splitlines(),
                expected.splitlines(),
                fromfile=str(output_path),
                tofile="generated",
                lineterm="",
            )
        )
        raise TypeGenerationError(f"Generated {label} types are out of date:\n{diff}")


class TypeScriptGenerator:
    def __init__(self, schemas: dict[str, dict[str, Any]]):
        self.schemas = schemas
        self.schema_names = {name: type_name_for_schema(schema, name) for name, schema in schemas.items()}
        self.schema_ids = {schema["$id"]: self.schema_names[name] for name, schema in schemas.items()}

    def generate(self) -> str:
        lines = [
            "/* eslint-disable */",
            "// Generated by contracts/generate_types.py. Do not edit manually.",
            "",
            "export type JsonPrimitive = string | number | boolean | null;",
            "export type JsonObject = { [key: string]: JsonValue };",
            "export type JsonArray = JsonValue[];",
            "export type JsonValue = JsonPrimitive | JsonObject | JsonArray;",
            "",
        ]

        for name in sorted(self.schemas):
            schema = self.schemas[name]
            root_name = self.schema_names[name]
            lines.extend(self.render_named_type(root_name, schema, root_name))
            lines.append("")
            for def_name, def_schema in sorted(schema.get("$defs", {}).items()):
                lines.extend(self.render_named_type(f"{root_name}{pascal_case(def_name)}", def_schema, root_name))
                lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def render_named_type(self, name: str, schema: dict[str, Any], root_name: str) -> list[str]:
        type_value = self.render_type(schema, root_name)
        if type_value.startswith("{\n"):
            return [f"export interface {name} {type_value}"]
        return [f"export type {name} = {type_value};"]

    def render_type(self, schema: dict[str, Any], root_name: str) -> str:
        if "$ref" in schema:
            return self.render_ref(schema["$ref"], root_name)
        if "const" in schema:
            return literal(schema["const"])
        if "enum" in schema:
            return " | ".join(literal(value) for value in schema["enum"])

        schema_type = schema.get("type")
        if isinstance(schema_type, list):
            return " | ".join(self.render_type({"type": item}, root_name) for item in schema_type)
        if schema_type == "string":
            return "string"
        if schema_type in {"number", "integer"}:
            return "number"
        if schema_type == "boolean":
            return "boolean"
        if schema_type == "null":
            return "null"
        if schema_type == "array":
            return f"{self.render_type(schema.get('items', {}), root_name)}[]"
        if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
            return self.render_object(schema, root_name)

        return "JsonValue"

    def render_ref(self, ref: str, root_name: str) -> str:
        if ref.startswith("#/$defs/"):
            return f"{root_name}{pascal_case(ref.removeprefix('#/$defs/'))}"
        if ref in self.schema_ids:
            return self.schema_ids[ref]
        raise TypeGenerationError(f"Unsupported JSON Schema reference: {ref}")

    def render_object(self, schema: dict[str, Any], root_name: str) -> str:
        properties = schema.get("properties", {})
        additional = schema.get("additionalProperties", None)
        if not properties:
            if additional is True:
                return "Record<string, JsonValue>"
            if isinstance(additional, dict):
                return f"Record<string, {self.render_type(additional, root_name)}>"
            return "{}"

        required = set(schema.get("required", []))
        lines = ["{"]
        for prop_name, prop_schema in properties.items():
            marker = "" if prop_name in required else "?"
            prop_type = self.render_type(prop_schema, root_name).replace("\n", "\n  ")
            lines.append(f"  {prop_name}{marker}: {prop_type};")
        if additional is True:
            lines.append("  [key: string]: JsonValue;")
        elif isinstance(additional, dict):
            lines.append(f"  [key: string]: {self.render_type(additional, root_name)};")
        lines.append("}")
        return "\n".join(lines)


class PythonGenerator:
    def __init__(self, schemas: dict[str, dict[str, Any]]):
        self.schemas = schemas
        self.schema_names = {name: type_name_for_schema(schema, name) for name, schema in schemas.items()}
        self.schema_ids = {schema["$id"]: self.schema_names[name] for name, schema in schemas.items()}

    def generate(self) -> str:
        lines = [
            "# Generated by contracts/generate_types.py. Do not edit manually.",
            "from __future__ import annotations",
            "",
            "from typing import Any, Literal, NotRequired, TypeAlias, TypedDict",
            "",
            "",
            "JsonPrimitive: TypeAlias = str | int | float | bool | None",
            "JsonObject: TypeAlias = dict[str, \"JsonValue\"]",
            "JsonArray: TypeAlias = list[\"JsonValue\"]",
            "JsonValue: TypeAlias = JsonPrimitive | JsonObject | JsonArray",
            "",
        ]

        for name in sorted(self.schemas):
            schema = self.schemas[name]
            root_name = self.schema_names[name]
            lines.extend(self.render_named_type(root_name, schema, root_name))
            lines.append("")
            for def_name, def_schema in sorted(schema.get("$defs", {}).items()):
                lines.extend(self.render_named_type(f"{root_name}{pascal_case(def_name)}", def_schema, root_name))
                lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def render_named_type(self, name: str, schema: dict[str, Any], root_name: str) -> list[str]:
        if self.is_typed_dict(schema):
            return self.render_typed_dict(name, schema, root_name)
        return [f"{name}: TypeAlias = {self.render_type(schema, root_name)}"]

    def is_typed_dict(self, schema: dict[str, Any]) -> bool:
        return (schema.get("type") == "object" or "properties" in schema) and bool(schema.get("properties"))

    def render_typed_dict(self, name: str, schema: dict[str, Any], root_name: str) -> list[str]:
        required = set(schema.get("required", []))
        lines = [f"class {name}(TypedDict):"]
        for prop_name, prop_schema in schema.get("properties", {}).items():
            prop_type = self.render_type(prop_schema, root_name)
            if prop_name in required:
                lines.append(f"    {prop_name}: {prop_type}")
            else:
                lines.append(f"    {prop_name}: NotRequired[{prop_type}]")
        return lines

    def render_type(self, schema: dict[str, Any], root_name: str) -> str:
        if "$ref" in schema:
            return self.render_ref(schema["$ref"], root_name)
        if "const" in schema:
            return f"Literal[{python_literal(schema['const'])}]"
        if "enum" in schema:
            return f"Literal[{', '.join(python_literal(value) for value in schema['enum'])}]"

        schema_type = schema.get("type")
        if isinstance(schema_type, list):
            return " | ".join(self.render_type({"type": item}, root_name) for item in schema_type)
        if schema_type == "string":
            return "str"
        if schema_type == "integer":
            return "int"
        if schema_type == "number":
            return "int | float"
        if schema_type == "boolean":
            return "bool"
        if schema_type == "null":
            return "None"
        if schema_type == "array":
            return f"list[{self.render_type(schema.get('items', {}), root_name)}]"
        if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
            return self.render_object(schema, root_name)

        return "JsonValue"

    def render_ref(self, ref: str, root_name: str) -> str:
        if ref.startswith("#/$defs/"):
            return f"{root_name}{pascal_case(ref.removeprefix('#/$defs/'))}"
        if ref in self.schema_ids:
            return self.schema_ids[ref]
        raise TypeGenerationError(f"Unsupported JSON Schema reference: {ref}")

    def render_object(self, schema: dict[str, Any], root_name: str) -> str:
        additional = schema.get("additionalProperties", None)
        if isinstance(additional, dict):
            return f"dict[str, {self.render_type(additional, root_name)}]"
        return "dict[str, JsonValue]"


def generate_typescript(manifest_path: Path = DEFAULT_MANIFEST) -> str:
    manifest = load_manifest(manifest_path)
    schemas = load_schemas(manifest)
    return TypeScriptGenerator(schemas).generate()


def generate_python(manifest_path: Path = DEFAULT_MANIFEST) -> str:
    manifest = load_manifest(manifest_path)
    schemas = load_schemas(manifest)
    return PythonGenerator(schemas).generate()


def write_typescript(output_path: Path, manifest_path: Path = DEFAULT_MANIFEST) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate_typescript(manifest_path), encoding="utf-8")


def write_python(output_path: Path, manifest_path: Path = DEFAULT_MANIFEST) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate_python(manifest_path), encoding="utf-8")


def check_typescript(output_path: Path, manifest_path: Path = DEFAULT_MANIFEST) -> None:
    check_output(output_path, generate_typescript(manifest_path), "TypeScript")


def check_python(output_path: Path, manifest_path: Path = DEFAULT_MANIFEST) -> None:
    check_output(output_path, generate_python(manifest_path), "Python")


def write_all(
    manifest_path: Path = DEFAULT_MANIFEST,
    typescript_output: Path = DEFAULT_TYPESCRIPT_OUTPUT,
    python_output: Path = DEFAULT_PYTHON_OUTPUT,
) -> None:
    write_typescript(typescript_output, manifest_path)
    write_python(python_output, manifest_path)


def check_all(
    manifest_path: Path = DEFAULT_MANIFEST,
    typescript_output: Path = DEFAULT_TYPESCRIPT_OUTPUT,
    python_output: Path = DEFAULT_PYTHON_OUTPUT,
) -> None:
    check_typescript(typescript_output, manifest_path)
    check_python(python_output, manifest_path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate contract types from JSON Schemas.")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--target", choices=["all", "typescript", "python"], default="all")
    parser.add_argument("--typescript-output", type=Path, default=DEFAULT_TYPESCRIPT_OUTPUT)
    parser.add_argument("--python-output", type=Path, default=DEFAULT_PYTHON_OUTPUT)
    parser.add_argument("--check", action="store_true", help="Check generated output without writing files.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        if args.check:
            if args.target == "typescript":
                check_typescript(args.typescript_output, args.manifest)
            elif args.target == "python":
                check_python(args.python_output, args.manifest)
            else:
                check_all(args.manifest, args.typescript_output, args.python_output)
        elif args.target == "typescript":
            write_typescript(args.typescript_output, args.manifest)
        elif args.target == "python":
            write_python(args.python_output, args.manifest)
        else:
            write_all(args.manifest, args.typescript_output, args.python_output)
    except Exception as exc:  # noqa: BLE001 - CLI should report any generation failure cleanly.
        print(f"Type generation failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
