# Generated by Django 5.2.13 on 2026-06-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentPackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("package_id", models.SlugField(max_length=100)),
                ("app_id", models.SlugField(max_length=80)),
                ("app_version", models.CharField(max_length=80)),
                ("runtime_min_version", models.CharField(max_length=80)),
                ("runtime_max_version", models.CharField(max_length=80)),
                ("platform_version", models.CharField(blank=True, max_length=80)),
                ("channel", models.CharField(default="dev", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[("signed", "Signed"), ("active", "Active"), ("archived", "Archived")],
                        db_index=True,
                        default="signed",
                        max_length=16,
                    ),
                ),
                ("package_hash", models.CharField(max_length=80)),
                ("signature", models.TextField()),
                ("payload", models.JSONField()),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
            ],
            options={
                "ordering": ["tenant__slug", "app_id", "channel", "package_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="deploymentpackage",
            constraint=models.UniqueConstraint(fields=("tenant", "package_id"), name="unique_package_id_per_tenant"),
        ),
        migrations.AddConstraint(
            model_name="deploymentpackage",
            constraint=models.UniqueConstraint(
                fields=("tenant", "app_id", "app_version", "channel"),
                name="unique_package_version_per_channel",
            ),
        ),
    ]
