# Generated by Django 5.2.13 on 2026-06-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_packages', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentpackage',
            name='channel',
            field=models.CharField(choices=[('dev', 'Development'), ('test', 'Test'), ('staging', 'Staging'), ('production', 'Production')], default='dev', max_length=16),
        ),
        migrations.CreateModel(
            name='DeploymentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('dev', 'Development'), ('test', 'Test'), ('staging', 'Staging'), ('production', 'Production')], max_length=16)),
                ('display_name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__slug', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'channel'), name='unique_deployment_channel_per_tenant')],
            },
        ),
    ]
