# Generated by Django 5.2.13 on 2026-06-09 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('kind', models.CharField(choices=[('action', 'Action'), ('app', 'App'), ('deployment_package', 'Deployment package'), ('field', 'Field'), ('form', 'Form'), ('screen', 'Screen'), ('theme', 'Theme')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__slug', 'kind', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='v1', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('payload', models.JSONField()),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_revisions', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='configurations.configurationdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['definition_id', 'revision'],
            },
        ),
        migrations.AddField(
            model_name='configurationdefinition',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='configurations.configurationrevision'),
        ),
        migrations.AddConstraint(
            model_name='configurationrevision',
            constraint=models.UniqueConstraint(fields=('definition', 'revision'), name='unique_configuration_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='configurationdefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'kind', 'key'), name='unique_configuration_definition_key'),
        ),
    ]
