# Generated by Django 5.2.13 on 2026-06-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=80)),
                ('schema_version', models.CharField(default='v1', max_length=16)),
                ('plugin_api_version', models.PositiveIntegerField()),
                ('platform_min_version', models.CharField(max_length=80)),
                ('platform_max_version', models.CharField(blank=True, max_length=80)),
                ('manifest', models.JSONField()),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('enabled', 'Enabled'), ('disabled', 'Disabled'), ('deprecated', 'Deprecated')], db_index=True, default='registered', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module_id', 'version'],
                'constraints': [models.UniqueConstraint(fields=('module_id', 'version'), name='unique_module_registration_version')],
            },
        ),
    ]
