# Generated by Django 5.2.13 on 2026-06-18 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('workflow_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_key', models.SlugField(max_length=120)),
                ('subject', models.CharField(max_length=200)),
                ('current_state', models.SlugField(max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflow_builder.workflowrevision')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflow_builder.workflowdefinition')),
            ],
            options={
                'ordering': ['tenant__slug', 'status', 'due_at', 'task_key'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'task_key'), name='unique_workflow_task_key_per_tenant')],
            },
        ),
    ]
