# Generated by Django 5.2.13 on 2026-06-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('workflow_builder', '0002_workflowtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('role', 'Role'), ('user', 'User'), ('expression', 'Expression')], max_length=16)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('user_id', models.CharField(blank=True, max_length=120)),
                ('expression', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workflow_builder.workflowtask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__slug', 'task_id', 'assignment_type', 'id'],
            },
        ),
    ]
