# Generated by Django 5.2.13 on 2026-06-18 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('workflow_builder', '0003_workflowtaskassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_id', models.SlugField(max_length=80)),
                ('trigger_type', models.CharField(max_length=32)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='workflow_builder.workflowrevision')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='workflow_builder.workflowdefinition')),
            ],
            options={
                'ordering': ['tenant__slug', 'workflow_id', 'trigger_id'],
                'constraints': [models.UniqueConstraint(fields=('revision', 'trigger_id'), name='unique_workflow_trigger_id_per_revision')],
            },
        ),
    ]
