# Generated by Django 5.2.13 on 2026-06-18 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('workflow_builder', '0004_workflowtrigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('workflow_started', 'Workflow started'), ('task_created', 'Task created'), ('task_assigned', 'Task assigned'), ('transition_applied', 'Transition applied'), ('task_completed', 'Task completed'), ('workflow_completed', 'Workflow completed')], db_index=True, max_length=32)),
                ('state_id', models.SlugField(blank=True, max_length=80)),
                ('transition_id', models.SlugField(blank=True, max_length=80)),
                ('actor', models.CharField(blank=True, max_length=160)),
                ('message', models.CharField(max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_logs', to='workflow_builder.workflowrevision')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_logs', to='workflow_builder.workflowtask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_logs', to='workflow_builder.workflowdefinition')),
            ],
            options={
                'ordering': ['tenant__slug', '-created_at', '-id'],
            },
        ),
    ]
