# Generated by Django for the initial identity/RBAC baseline.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PlatformRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant"),
                ),
            ],
            options={
                "ordering": ["tenant__slug", "slug"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="identity.platformpermission"),
                ),
                (
                    "role",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="identity.platformrole"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="platformrole",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                through="identity.RolePermission",
                to="identity.platformpermission",
            ),
        ),
        migrations.CreateModel(
            name="UserRoleAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="identity.platformrole"),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["tenant__slug", "user_id", "role__slug"],
            },
        ),
        migrations.AddConstraint(
            model_name="platformrole",
            constraint=models.UniqueConstraint(fields=("tenant", "slug"), name="unique_role_slug_per_tenant"),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(fields=("role", "permission"), name="unique_permission_per_role"),
        ),
        migrations.AddConstraint(
            model_name="userroleassignment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user", "role"),
                name="unique_role_assignment_per_tenant_user",
            ),
        ),
    ]
